- README.md
- Sources/Vitamin/Foundations/Icons/Vitamix.swift
- Sources/Vitamin/Foundations/Typography/Fonts.swift
- Sources/Vitamin/Utils/SwiftGen/swiftgen.yml
- Vitamin.podspec
Before pushing to cocoapods, we need to run `pod lib lint`
And this enlightened that.... the project does not compile if not in SPM context (typically, for Cocoapods)
To fix that, I had to :
- change the SwiftGen configuration for Fonts and Icons
- add the swift version in podspec (5.3)
The validation now passes, so once this PR merged, I will be able to push it to Cocoapods trunk repo
After discussion with @lauthieb , I also modified the README to encourage users to use an exact version of Vitamin in their project (with SPM and Cocoapods)
> fix(cocoapods): fix to pass cocoapods podspec validation

- README.md
Add new image adaptation for dark mode
Details: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
> docs(readme): add new image adaptation for dark mode

- Package.swift
- README.md
- Showcase/Application/Foundations/Shadows/Cell/ShadowTableViewCell.swift
- Showcase/Application/Foundations/Shadows/Cell/ShadowTableViewCell.xib
- Showcase/Application/Foundations/Shadows/ShadowsViewController.swift
- Showcase/Application/Main/MainTableViewController.swift
- Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
- Sources/Vitamin/Foundations/Shadows/README.md
- Sources/Vitamin/Foundations/Shadows/Shadows.swift
Here is a proposal for shadow implementatiion.
I had to do a little research because the snippet generated by Figma was irrelevant.
Indeed, Figma uses notion of blur ans spread, which are not native for iOS.
I found some blog post about converting blur and spread from Sketch to iOS, and their method seems to work also for Figma.
I provided a quick README for shadows, and referenced this file in general README
The Showcase has been updated, with an example of shadow dropped under a rounded rect label, with Background.accent color. But the shadow should be applicable to any UIView.
The color of the shadow is the same for dark and light themes (could not find in Figma if I should use a specific color for dark theme), thus, the shadow is quite invisible in dark theme over a black background.
> feat(shadows): add shadow foundation

- .github/ISSUE_TEMPLATE/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_improvements_request.md
- .github/ISSUE_TEMPLATE/new_component_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/semantic.yml
- CONTRIBUTING.md
- CONTRIBUTORS.md
The goal is to align our GitHub different configuration files between `vitamin-(web|android|ios)` stacks.
This PR is there to enhance the contributor experience and facilitate onboarding for developers.
- No
> docs(.github): add configuration files

- Sources/Vitamin/Components/Switch/VitaminSwitch.swift
Findings:
On vitamin, toggle button switch from white to dark depending on the theme selected
Toggle button on iOS dark mode is still white (there is no color switch).
Proposal
In order to respect the platform as much as possible, I propose to replace the semantic coloring by a color base
- No
> refactor: replace toggle color for dark mode #29

- Showcase/Application/Foundations/Shadows/Cell/ShadowTableViewCell.swift
- Sources/Vitamin/Foundations/Typography/TextStyles.swift
Refacto `TextStyle` to expose more easily the needed informations like font or size. This is needed to start `SwiftUI` version of the `TextStyle` to avoid duplications.  
This PR also fix a line height issue with large accessibility font size.
In some case when need to access to some informations like `font` or `size` and it was currently not easy.
- No
No changes on the UI, big changes in code.
| Before | After |
| ------ | ------ |
| ![Before_1](https://user-images.githubusercontent.com/87971589/151042768-30dba418-00e2-4a3b-9221-4ce17a682a1f.png) | ![After_1](https://user-images.githubusercontent.com/87971589/151043022-b3177813-1057-4cb4-8325-8763ce4f8f90.png)|
| ![Before_2](https://user-images.githubusercontent.com/87971589/151042765-877a9eb1-1a60-4706-a32a-b5f6a25bcbdb.png) | …
> refactor: update TextStyle component to prepare next components

- Package.swift
- README.md
- Showcase/Application/Foundations/Radiuses/Cell/RadiusTableViewCell.swift
- Showcase/Application/Foundations/Radiuses/Cell/RadiusTableViewCell.xib
- Showcase/Application/Foundations/Radiuses/RadiusViewController.swift
- Showcase/Application/Foundations/Shadows/Cell/ShadowTableViewCell.swift
- Showcase/Application/Main/MainTableViewController.swift
- Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
- Sources/Vitamin/Foundations/Radiuses/README.md
- Sources/Vitamin/Foundations/Radiuses/Radiuses.swift
Add a VitaminRadius enum to define all allowed corner radiuses as constants
This PR resolves #8 , by providing fixed corner radius for every view
- No
I explored many ideas for this foundation, such as a method that would directly modify the corner radius of any view, but that felt a little too invasive to me.
I preferred just defining the correct values in an enum, and let the developer use them (every iOS developer should know how to apply a radius to a view ;) )
I also hesitated for the `VitaminRadius` between two solution :
- directly inherit from CGFloat and use the `rawValue'
- define a computed property of type CGFloat and use this property
Finallyn the first one felt more intuitive, but i am open to discussion.
Note : After discussion with @lauthieb , I took advantage of this PR …
> feat(foundations): radius implementation

- .github/workflows/PullRequestLabeledForDesignReview.yml
- .gitignore
- Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
- bitrise.yml
Add a Github action to launch a build of the showcase when the PR is considered as OK on a technical point of view, thus ready for functional review by designers.
NOTE : the build is not launched on the Decathlon Public Bitrise account, thus, the workflow is not stored in the bitrise.yml file of the repo
This PR aims to provide a showcase app on each PR to ease the design review.
The showcase will be built only when :
- the PR is tagged with the 'Ready for Design Review' label
- the PR is updated (new commit, change base branch,...) since it is already labeled with 'Ready for Design Review'
The build will be made available on the private channel #vitamin-ios-functional-reveiws of the Decathlon Design System slack.
It aims to handle the #27 issue : resolves #27
- No
Slack Notification on …
> chore(showcase): build showcase - deploy on bitrise - slack

- Showcase/Application/Components/Progressbar/Cell/ProgressbarTableViewCells.swift
- Showcase/Application/Components/Progressbar/ProgressbarViewController.swift
- Sources/Vitamin/Components/Progressbar/VitaminProgressbar.swift
This PR contain improvement of progress bar accessibility. 
They might be some optimization to do for example : 
* How to copy localized string of standard UIProgressView (not sure how to do it with Swift)
Progress bar was not accessible with voiceover, meaning that if a blind user encounter a Progress there were no focus on this element so the user has no idea of what's going on. 
What I have done is : 
* Letting end user add custom accessibilityLabel for exemple "Loading new products in progress".
* announcing percentage update in accessibilityValue
* If no custom accessibilityLabel, setting UIProgressView default accessibilityLabel
What could be improved : 
* swift syntax probably as it is not my main language.
* add an animated progress bar in Showcase to validate that value is well …
> fix: proposal for accessibility of progress bar

- Showcase/Application/UIKit/Components/Button/Cell/ButtonTableViewCell.swift
- Showcase/Application/UIKit/Components/Button/Cell/ButtonTableViewCell.xib
- Sources/VitaminUIKit/Components/Button/README.md
- Sources/VitaminUIKit/Components/Button/VitaminButton+Deprecated.swift
- Sources/VitaminUIKit/Components/Button/VitaminButton.swift
I added the ability to define a 'icon Alone' version of VitaminButton.
I also reworked the way to specify which type of icon you want (for already existing trailing and leading icons)
And I took advantage of this PR to change icon size on large and medium button (see #74)
- This PR solves #52
- It also solves #74
- No
I deprecated some methods, but they are still usable, the will just raise a warning.
I am not sure it is Vitamin compliant, but I reworked the code to give the ability to have different icons for different states (that was allowed before by the previous code, but did not work well)
> feat(button): add icon alone UIKit VitaminButton type, and refactor icon management

- Package.swift
- Sources/VitaminSwiftUI/Utils/View/View+Preview.swift
This PR adds a helper to be able to use custom fonts in SwiftUI preview (only on Xcode 14 for now)
Until now using custom fonts on SwiftUI previews breaks the preview (crash)
- No
> feat: Adding helper to use Custom Fonts on SwiftUI previews

- Sources/VitaminCore/Foundations/Assets/VitaminAssets+Flags.swift
- Sources/VitaminCore/Foundations/Assets/VitaminAssets.swift
- Sources/VitaminCore/Foundations/Icons/Vitamix.swift
- Sources/VitaminCore/Utils/SwiftGen/images.stencil
I've edited the SwiftGen images template to add a property `optionalImage: UIImage?` to `VitaminAsset` (and `Vitamix`)
Currently, there is a crash when trying to access a country flag that doesn't exist.
- No
> fix: crash with country flags

- Showcase/Application/UIKit/Components/Button/Cell/ButtonTableViewCell.swift
- Showcase/Application/UIKit/Components/Tag/Cell/TagTableViewCell.swift
- Sources/VitaminCore/Components/Button/VitaminButtonSize.swift
- Sources/VitaminUIKit/Components/Button/VitaminButton.swift
- Sources/VitaminUIKit/Components/TextField/VitaminTextField.swift
Add the method `init(frame: CGRect)` to fix the crash.
I also fix warnings in the project.
We cannot use `VitaminButton` as `IBDesignable` because of a missing method.
- No
> fix: crash vitamin button ibdesignable

- Sources/VitaminCore/Foundations/Typography/TextStyles.swift
- Sources/VitaminUIKit/Components/Progressbar/VitaminProgressbarVariant.swift
- Sources/VitaminUIKit/Components/TextField/VitaminTextField.swift
- Sources/VitaminUIKit/Foundations/Typography/README.md
Currently the `VitaminTextStyle` doesn't handle line break mode.
- No but a variable is now deprecated.
> feat: add line break mode option to UIKit VitaminTextStyle

- Showcase/Application/UIKit/Components/Progressbar/ProgressbarViewController.swift
- Sources/VitaminUIKit/Components/Progressbar/README.md
- Sources/VitaminUIKit/Components/Progressbar/VitaminProgressbar.swift
- Sources/VitaminUIKit/Components/Progressbar/VitaminProgressbarVariant.swift
After integration in a project, I propose small improvements on the progress bar in UIKit version : 
- fix the linear progress bar track width : rounded caps were out of frame, and were hidden if the enclosing view had clipToBounds = true
- add the ability to display a label above `.indeterminate` linear toolbar
- add the ability to easily swicth between `.determinate` and `.indeterminate` progress type 
After integration in the connected locker project (Decathlon CSP team), we noticed some little improvements
- No
no need for screenshots
Nothing to add
> feat: progress bar improvements

- Sources/VitaminSwiftUI/Foundations/Typography/Typography+SwiftUI.swift
I fixed the line height calculation to get the correct value.
The line height when using the `.vitaminTextStyle` modifier was not correct.
- No
| Before | After |
| ------- | ---- |
| ![Before](https://user-images.githubusercontent.com/87971589/195650173-1fd9de77-7756-4637-b5f1-d52bb9d39cdc.png) | ![After](https://user-images.githubusercontent.com/87971589/195650214-83c26f39-34b2-4502-88b3-cdcb792feffb.png) |
| With dynamic type enabled | |
| ![Before 1](https://user-images.githubusercontent.com/87971589/195651470-a721380b-ff99-4465-984d-3480dcd97ec1.png) | ![After 1](https://user-images.githubusercontent.com/87971589/195651515-2c9bfc4e-5200-4487-a88f-479ab54fd444.png) |
> fix: SwiftUI TextStyle modifier line height

- Sources/VitaminUIKit/Components/TextField/README.md
- Sources/VitaminUIKit/Components/TextField/VitaminTextField+Configuration.swift
- Sources/VitaminUIKit/Components/TextField/VitaminTextField.swift
- Sources/VitaminUIKit/Components/TextField/VitaminTextField.xib
Horizontal leading and trailing padding are added to VitaminTextField.
The aim of this PR is to allow removing these padding if desired (and keeping them by default for retrcompatibility).
For that, a new boolean property named `horizontalPadding` has been added to VitaminTextField.
Its default value is `true` (for backward compatibility), and can be set to false either in constructor, of afterwards.
Fixes #89 
- No
> fix: allow removing horizontal padding on VitaminTextField

- Sources/VitaminSwiftUI/Utils/UIColor+SwiftUI.swift
Add a condition to avoid code that can crash.
We have a crash when we try to use a `VitaminButtonUIStyle` on a button with  style `.primary` and `.ghost`.
- No
N/A
> fix: crash for swiftui color

- Sources/VitaminUIKit/Components/Button/VitaminButton.swift
When title is set, we re-enforce the title color to avoid weird effects like described in #101
fixes #101 
- No
> fix: enforce title color when title is set to avoid weird behaviours

- Sources/VitaminSwiftUI/Components/TextField/VitaminTextFieldModifier.swift
Now, we update the text value only when the value changes.
When we add a counter in the SwiftUI TextField, the text is always updated, even when there is no changes.
- No
> fix: SwiftUI TextField - loop issue with characters counter

- README.md
- Vitamin.podspec
- VitaminCore.podspec
- VitaminSwiftUI.podspec
- bitrise.yml
Reintegrate 0.10.0 tag generated by bitrise workflow to main
Have the latest version for cocoapods on main
- No
> chore: bump to 0.10.0

- Sources/VitaminCore/Components/TextField/VitaminTextFieldState.swift
This PR fixes the text color of the UIKit VitaminTextField component in enable mode.
The color for enable mode was tertiary instead of primary.
You can see it on the screen below in the first textfield, i tapped "TEST TEST" and the text color is tertiary.
- No
e
> fix: UIKit VitaminTextfield text color

- Sources/VitaminUIKit/Components/Button/VitaminButton.swift
Add and set `tintAdjustmentMode` property to `.normal` for the `imageView` of `VitaminButton`
The image tint color is changing when a `UIAlertController` is presented. Setting `tintAdjustmentMode` to `.normal` fix this problem. 
You can see the change in the before/after provided in the screenshots section of this PR. 
- No
As you can see below the tint color of the icon stay the same with an AlertController presented.
Before | After
--- | ---
> fix: set tintAdjustmentMode to .normal

- Showcase/Application/SwiftUI/Components/Button/ButtonsView.swift
- Sources/VitaminSwiftUI/Components/Button/README.md
- Sources/VitaminSwiftUI/Components/Button/VitaminButton.swift
Add full width support for SwiftUI button
Currently, SwiftUI button can't be sized to full width using `.frame(maxWidth: .infinity)`.
- No
> feat: swiftui fullwidth button
